### PR TITLE
Add behavior to edit hero biography and username

### PR DESCRIPTION
**Pull request by recursion**
Real time bio/username editing (careful because this is your username for signin)

### CODE REVIEW

**Comment by Asxen** [comment]
Yeah, I didn't catch that it was the username until last second. This is definitely something we'll want to point out and hopefully let other teams fix up; it's a pretty critical hacking weakness to have your username literally on display lol.

**Comment by recursion** [comment]
Yeah so its pretty trivial to change this in any number of ways. 
It was done this way because it was literally the quickest implementation method at the time.

**Comment by recursion** [comment]
I would say adding an author name category to the user entry in the DB, and using that for display probably makes the most sense.

**Comment by Asxen** [comment]
I figured as much, it just caught me off guard when I was doing a hot presentation off-the-cuff. It's just worth mentioning to anyone that may pick up our project and letting them use a different implementation; we still need to give any legacy groups something to do, neh?

**Comment by recursion** [comment]
Yes - this detail needs to go  into the readme - along with some details about how pretty urls are working (and what their limitations are currently)

**Pull request merged**
