### PR TITLE
Our contributions to a great project

### PR DESCRIPTION
**Pull request by mnaamani**

### CODE REVIEW

**Comment by recursion** [comment]
So I didn't want to merge this PR without everyone on ArmorAndMint agreeing to it. But I think its a great PR - I fully support merging, and would love to do so as long as all team members agree!

**Comment by seangrogg** [comment]
I see no reason not to - they added several amazing features to the project. I'm genuinely overwhelmed.

**Comment by brukh** [comment]
I have no objections, great job guys :+1:

**Comment by recursion** [comment]
Fantastic!

**Pull request merged**
