### PR TITLE
Client side - Resized content & implemented buttons to edit posts & header info (bio)

### PR DESCRIPTION
**Pull request by brukh**
+ Client side - Resized content & implemented buttons to edit posts & header info (bio).
+ Updated index to reflect changes from michael's PR
+ Gave the page more structure & added external library scripts.

### CODE REVIEW

**Comment by recursion** [comment]
It appears that you are trying to commit  the .idea directory instead of .gitignore.
This needs to be resolved before commit.
You are also adding back in a .orig file which I guess is left over from one of your merges?
Either way that should also not be in this PR.

**Comment by brukh** [comment]
Isn't the .idea being added to the gitignore file? And let me delete those files & submit another request.

**Comment by recursion** [comment]
There are still 2 .orig files being submitted here.

**Comment by recursion** [comment]
Looks like this will need to be rebased again (cannot merge as is). Shouldn't be a big deal since the only diff should be in the .gitignore, otherwise looks good.

**Pull request merged**
